# -*- coding: utf-8 -*-
"""extract.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ByxVl8RzTSA0RPczB1egYT831Ot9rBfg
"""

from google.colab import drive
import pandas as pd
from sqlalchemy import create_engine

drive.mount('/content/drive')

"""Extract data from landing zone"""

def extract_by_month(month,year):
  timestamp = month + year
  df_usage = pd.read_csv('/notebooks/landing/persistent/'+timestamp+'/usageData.csv', index_col=0)
  df_strata = pd.read_csv('/notebooks/landing/persistent/'+timestamp+'/strataData.csv', index_col=0)
  return df_usage, df_strata

df_usage, df_strata = extract_by_month('January','2022')

df_usage.head()

df_strata.head()

"""Removing unnecesary columns and renaming fields to match database schema"""

df_usage = df_usage.rename(columns = {'CHIP':'landCode', 'BARMANP':'zoneCode', 'LOCALID':'locationCode', 
                           'DESTINO':'mainUsage', 'AREA_TE':'totalArea', 'AREA_CO': 'builtArea',
                           'AVLO_2019':'price'})

df_strata = df_strata.rename(columns = {'ESoChip':'landCode', 'ESoCLote':'areaCode', 'ESoEstrato':'stratumCode'})

"""Loading data into the Formatted Zone"""

postgres_str = ('postgresql://postgres:OaklandStreet@localhost:5432/FormattedZone')
cnx = create_engine(postgres_str)
df_usage.to_sql('usageData', cnx, if_exists='replace')
df_strata.to_sql('strataData', cnx, if_exists='replace')
cnx