# -*- coding: utf-8 -*-
"""Schema.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17GhxyN0ycquZggxRYPBBYqbWf-pzzUrd

Formatted zone sch
"""

create table usageData(
	landCode char(15) not null,
	zoneCode bigint,
	locationCode integer,
	mainUSage char(50),
	totalArea numeric(2),
	builtArea numeric (2),
	price bigint,
	primary key (landCode)
)

create table stratification(
	landCode char(15) not null,
	areaCode bigint,
	stratumCode integer,
	primary key (landCode),
	foreign key (landCode) references usageData(landCode)
)

from google.colab import drive
import pandas as pd
from sqlalchemy import create_engine
drive.mount('/content/drive')

"""Reading data from formatted zone and profiling"""

postgres_str = ('postgresql://postgres:OaklandStreet@localhost:5432/FormattedZone')
cnx = create_engine(postgres_str)
df_usage = pd.read_sql('SELECT * FROM usageData', cnx)
df_strata = pd.read_sql('SELECT * FROM strataData', cnx)
cnx

df_usage.describe()

df_strata.describe()