# -*- coding: utf-8 -*-
"""Deduplication.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TI5ZKP0EFVNIH2jlixX7fVMHkvj-Vd4j
"""

from google.colab import drive 
drive.mount('/content/gdrive')

#Setting libraries required for the notebook
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

#Retrieving input dataset

postgres_str = ('postgresql://postgres:OaklandStreet@localhost:5432/FormattedZone')
cnx = create_engine(postgres_str)
df = pd.read_sql('SELECT * FROM usageData', cnx)
df.shape

"""Removing duplicated data for input datasets:

"""

df2 = df.drop_duplicates(keep='last')
df2.shape

"""Removing NA Data"""

df3 = df2.dropna(axis=1)
df3.shape

postgres_str = ('postgresql://postgres:OaklandStreet@localhost:5432/TrustedZone')
cnx = create_engine(postgres_str)
df.to_sql('usageData', cnx, if_exists='replace')
cnx