# -*- coding: utf-8 -*-
"""merging.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aGHtOxPcsL4skTUUbnCEOXj9s9owXTrF
"""

from google.colab import drive
import pandas as pd
from sqlalchemy import create_engine

drive.mount('/content/drive')

"""Reading data from Trusted Zone"""

postgres_str = ('postgresql://postgres:OaklandStreet@localhost:5432/TrustedZone')
cnx = create_engine(postgres_str)
df_usage = pd.read_sql('SELECT * FROM usageData', cnx)
df_strata = pd.read_Sql('SELECT * FROM stratification', cnx)
df_usage.head()

"""Merging the data from the two data sources"""

df_targetUsageData = pd.merge(df_usage, df_strata, on='landCode')
df_targetUsageData.head()

"""Reordering columns to match with database schema"""

df_targetUsageData = df_targetUsageData[['landCode', 'zoneCode', 'locationCode', 'stratumCode', 'mainUsage', 'totalArea', 
                                         'builtArea', 'price', 'areaCode' ]]
df_targetUsageData = df_targetUsageData.drop('areaCode', axis=1)
df_targetUsageData.head()

"""Loading data into Exploitation Zone"""

postgres_str = ('postgresql://postgres:OaklandStreet@localhost:5432/ExploitationZone')
cnx = create_engine(postgres_str)
df_targetUsageData.to_sql('targetUsageData', cnx, if_exists='replace')
cnx