# -*- coding: utf-8 -*-
"""Schema.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EKtAn-bfsc-4YRROMSGeHLQmV0EykVVa

Explotation Zone schema
"""

create table targetUsageData(
	landCode char(15) not null,
	zoneCode bigint,
	locationCode integer,
	stratumCode integer,
	mainUSage char(50),
	totalArea numeric(2),
	builtArea numeric (2),
	price bigint,
	primary key (landCode)
)

from google.colab import drive
import pandas as pd
from sqlalchemy import create_engine
drive.mount('/content/drive')

"""Profiling"""

postgres_str = ('postgresql://postgres:OaklandStreet@localhost:5432/ExploitationZone')
cnx = create_engine(postgres_str)
df_targetUsageData.read_sql('targetUsageData', cnx, if_exists='replace')
cnx

df_targetUsageData.describe()