# This is a basic workflow to help you get started with Actions

name: DataProcessingWorkflow

on: [push]

jobs:
  upload-data-job:
    name: Update data 
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
        
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: execute extraction from landing zone
        run: ./notebooks/formatted/extract.py
      
      - name: execute deduplication
        run: ./notebooks/trusted/Deduplication.py
      
      - name: execute outlier detection
        run: ./notebooks/trusted/OutlierDetection.py
        
      - name: load data into exploitation zone
        run: ./notebooks/exploitation/merging.py
      
        
